blank_issues_enabled: false
contact_links:
  - name: Alternative contact methods
    url: https://sanelkukic.us.eu.org/contact
    about: If you wish to use an alternative contact method to reach me, you can view a full list on this website.
